global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications' # the receiver for alerts
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name:  'slack-notifications'
    slack_configs:
      - channel: '#all-lab' # your Slack channel
        api_url: "https://hooks.slack.com/services/" # your Slack webhooks URL
        send_resolved: true
