#SPDX-License-Identifier: MIT-0
---
# tasks file for prometheus_grafana_alertmanager

- name: Debug app_directory
  debug:
    var: api_directory

- name: Create a directory for the API code
  file:
    path: "{{ api_directory }}"
    state: directory
    mode: '0755'

- name: Copy necessary files to the VM
  synchronize:
    mode: push
    src: files/
    dest: "{{ api_directory }}"

- name: Generate alertmanager.yml from a template
  template:
    src: alertmanager.yml.j2
    dest: /app/alertmanager/alertmanager.yml

- name: List /app content
  shell: ls -l /app
  register: ls_output

- name: debug /app content
  debug:
    var: ls_output.stdout

- name: Ensure previous Docker containers are down
  shell: docker-compose -f {{ api_directory }}/docker-compose.yml down

- name: Ensure no containers are left
  shell: docker container prune --force

- name: Start services with docker-compose up
  shell: docker-compose -f {{ api_directory }}/docker-compose.yml up -d 
