#SPDX-License-Identifier: MIT-0
---
# tasks file for prometheus_grafana_alertmanager

- name: Debug app_directory
  ansible.builtin.debug:
    var: api_directory

- name: Create a directory for the API code
  ansible.builtin.file:
    path: "{{ api_directory }}"
    state: directory
    mode: '0755'

- name: Copy necessary files to the VM
  ansible.builtin.synchronize:
    mode: push
    src: files/
    dest: "{{ api_directory }}"

- name: Generate alertmanager.yml from a template
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /app/alertmanager/alertmanager.yml

- name: List /app content
  ansible.builtin.shell: ls /app
  register: ls_output

- name: debug /app content
  ansible.builtin.debug:
    var: ls_output.stdout

- name: Ensure previous Docker containers are down
  ansible.builtin.shell: docker-compose -f {{ api_directory }}/docker-compose.yml down

- name: Ensure no containers are left
  ansible.builtin.shell: docker container prune --force

- name: Start services with docker-compose up
  ansible.builtin.shell: docker-compose -f {{ api_directory }}/docker-compose.yml up -d 
